# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Map": "00_map.ipynb",
         "Transect": "00_map.ipynb",
         "Uhi": "01_uhi.ipynb",
         "OtherDf": "01_uhi.ipynb"}

modules = ["map.py",
           "uhi.py"]

doc_url = "https://raguileoam.github.io/ufro_uhi_plot/"

git_url = "https://github.com/raguileoam/ufro_uhi_plot/tree/master/"

def custom_doc_links(name): return None
